# Configuração do container para execução em outros computadores

# Define os serviços (contêineres) que compõem a sua aplicação.
services:
  # Serviço da API Node.js, baixado do Docker Hub
  app:
    # O Docker irá baixar esta imagem automaticamente se ela não existir localmente.
    container_name: task-management-api-nodejs
    image: kalbaitzer/task-management-api-nodejs:1.0
    ports:
      - "3000:3000"          # Mapeia a porta 3000 do contêiner para a porta 3000 da sua máquina
    env_file:
      - ./config/.env.docker # Carrega as variáveis de ambiente do arquivo .env
    depends_on:
      - mongo                # Garante que o contêiner do MongoDB inicie antes da API

  # Serviço do Banco de Dados MongoDB
  mongo:
    image: mongo:latest # Usa a imagem oficial mais recente do MongoDB
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeia a porta padrão do MongoDB
    volumes:
      - mongo-data:/data/db # Cria um volume para persistir os dados do banco

# Define o volume para persistência de dados do MongoDB
volumes:
  mongo-data: