##################################################################################
### Requisições para Usuários
##################################################################################

### createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Ednaldo Kalbaitzer",
  "email": "kalbaitzer@yahoo.com.br",
  "role": "Manager"
}

### createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "User 1",
  "email": "user1@gmail.com",
  "role": "User"
}

### getAllUsers
GET http://localhost:3000/api/users

### getUserById
GET http://localhost:3000/api/users/c437b4db-7473-49be-a674-13474a1f1b31

### updateUser
PUT http://localhost:3000/api/users/f3f92bfe-1a08-44d8-a222-43ff72a8ae4b
Content-Type: application/json

{
  "name": "Teste alteração 2",
  "email": "teste2@gmail.com",
  "role": "User"
}

### deleteUser
DELETE http://localhost:3000/api/users/dc2bf03d-68d7-49b3-b8d1-f34e95dbd100


##################################################################################
### Requisições para Projetos
##################################################################################

### createProject
POST http://localhost:3000/api/projects
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31
Content-Type: application/json

{
  "name": "Projeto Node.js Express + MongoDB",
  "description": "Gerencimento de Tarefas"
}

### createProject
POST http://localhost:3000/api/projects
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31
Content-Type: application/json

{
  "name": "Projeto 1",
  "description": "Descrição 1"
}

### getAllProjects
GET http://localhost:3000/api/projects
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31

### getProjectById
GET http://localhost:3000/api/projects/fc123d64-bdd0-4aa4-afa7-a8e9d7e59357
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31

### updateProject
PUT http://localhost:3000/api/projects/03078fc9-fbd9-4aab-857b-876034107087
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{
  "name": "Projeto 3",
  "description": "Descrição 3"
}

### deletProject
DELETE http://localhost:3000/api/projects/be1955f1-ef1d-45e5-8ed4-33290ad7ff5b
X-User-Id: e9d5d6fd-8d2c-4c3e-8d44-dfc246343d9e


##################################################################################
### Requisições para Tarefas
##################################################################################

### createTaskForProject
POST http://localhost:3000/api/tasks/projects/fc123d64-bdd0-4aa4-afa7-a8e9d7e59357
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31
Content-Type: application/json

{ 
  "title": "Tarefa 1", 
  "description": "Iniciar atividade 1",
  "dueDate": "2025-10-15T10:00:00Z", 
  "priority": "Alta"
}

### getTasksByProject
GET http://localhost:3000/api/tasks/projects/fc123d64-bdd0-4aa4-afa7-a8e9d7e59357
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31

### getTaskById
GET http://localhost:3000/api/tasks/bc916e4d-e6c4-41a2-a80a-1c75a7cdf05e
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31

### updateTask
PUT http://localhost:3000/api/tasks/bc916e4d-e6c4-41a2-a80a-1c75a7cdf05e
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31
Content-Type: application/json

{ 
  "title": "Tarefa 2 alterada", 
  "description": "Alterando tarefa 2 novamente",
  "dueDate": "2030-10-04T10:00:00Z",
  "status": "Concluida"
}

### updateTaskStatus
PATCH http://localhost:3000/api/tasks/e9e60b39-be39-4367-84da-52d57ccf29d7/status
X-User-Id: dc2bf03d-68d7-49b3-b8d1-f34e95dbd100
Content-Type: application/json

{ 
  "status": "Concluida"
}

### addComment
POST http://localhost:3000/api/tasks/2bf13943-2cb8-4b38-a0e6-42dca3fdef6d/comments
X-User-Id: e9d5d6fd-8d2c-4c3e-8d44-dfc246343d9e
Content-Type: application/json

{ 
  "comment": "Tarefa concluída com sucesso"
}

### getTaskHistory
GET http://localhost:3000/api/tasks/2bf13943-2cb8-4b38-a0e6-42dca3fdef6d/history
X-User-Id: e9d5d6fd-8d2c-4c3e-8d44-dfc246343d9e

### deleteTask
DELETE http://localhost:3000/api/tasks/3fda53f3-c9ca-4909-9365-15679df938c5
X-User-Id: e9d5d6fd-8d2c-4c3e-8d44-dfc246343d9e

##################################################################################
### Requisições para Relatórios
##################################################################################

### getPerformanceReport
GET http://localhost:3000/api/reports/performance
X-User-Id: c437b4db-7473-49be-a674-13474a1f1b31
