##################################################################################
### Requisições para Usuários
##################################################################################

### createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Ednaldo Kalbaitzer",
  "email": "kalbaitzer@yahoo.com.br",
  "role": "Manager"
}

### createUser
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "User 1",
  "email": "user1@gmail.com",
  "role": "User"
}

### getAllUsers
GET http://localhost:3000/api/users

### getUserById
GET http://localhost:3000/api/users/e888710c-5e56-457b-8703-3ca975a9c3b3

### updateUser
PUT http://localhost:3000/api/users/9a61522c-e5a4-47a7-b52c-9507aa72e4f2
Content-Type: application/json

{
  "name": "Teste alteração 2",
  "email": "teste2@gmail.com",
  "role": "User"
}

### deleteUser
DELETE http://localhost:3000/api/users/b03f0f94-468d-475d-a08f-98b2bcd859fb


##################################################################################
### Requisições para Projetos
##################################################################################

### createProject
POST http://localhost:3000/api/projects
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{
  "name": "Projeto Node.js Express + MongoDB",
  "description": "Gerencimento de Tarefas"
}

### createProject
POST http://localhost:3000/api/projects
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{
  "name": "Projeto 2",
  "description": "Descrição 2"
}

### getAllProjects
GET http://localhost:3000/api/projects
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

### getProjectById
GET http://localhost:3000/api/projects/dbdfb55b-41a2-43a1-9544-96911df062aa
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

### updateProject
PUT http://localhost:3000/api/projects/03078fc9-fbd9-4aab-857b-876034107087
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{
  "name": "Projeto 3",
  "description": "Descrição 3"
}

### deletProject
DELETE http://localhost:3000/api/projects/03078fc9-fbd9-4aab-857b-876034107087
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4


##################################################################################
### Requisições para Tarefas
##################################################################################

### createTaskForProject
POST http://localhost:3000/api/tasks/projects/03078fc9-fbd9-4aab-857b-876034107087
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{ 
  "title": "Tarefa 1", 
  "description": "Iniciar atividade 1",
  "dueDate": "2025-10-15T10:00:00Z", 
  "priority": "Alta"
}

### getTasksByProject
GET http://localhost:3000/api/tasks/projects/dbdfb55b-41a2-43a1-9544-96911df062aa
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

### getTaskById
GET http://localhost:3000/api/tasks/36037150-5757-4464-9d07-d2a62afabf1a
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

### updateTask
PUT http://localhost:3000/api/tasks/f9a9f077-1239-43c1-875f-e2ea24094929
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{ 
  "title": "Tarefa 5 alterada", 
  "description": "Alterando tarefa 5",
  "dueDate": "2026-10-04T10:00:00Z",
  "status": "Concluida"
}

### updateTaskStatus
PATCH http://localhost:3000/api/tasks/c3e6a198-9822-40f1-a29c-eeea89da4f1d/status
X-User-Id: b8aff0cb-e516-4b92-bfcc-2ddb9404c500
Content-Type: application/json

{ 
  "status": "Pendente"
}

### addComment
POST http://localhost:3000/api/tasks/452ffc95-349a-4cce-9ae9-c2e4c7988de2/comments
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4
Content-Type: application/json

{ 
  "comment": "bcbbfdd"
}

### getTaskHistory
GET http://localhost:3000/api/tasks/452ffc95-349a-4cce-9ae9-c2e4c7988de2/history
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

### deleteTask
DELETE http://localhost:3000/api/tasks/452ffc95-349a-4cce-9ae9-c2e4c7988de2
X-User-Id: d5a1a361-40f7-48ec-8b31-81ce17a990f4

##################################################################################
### Requisições para Relatórios
##################################################################################

### getPerformanceReport
GET http://localhost:3000/api/reports/performance
X-User-Id: 890ba404-71f3-4d43-b429-cae7d5551f98
